apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrepository.yaml
- helmrelease-metrics-server.yaml
- helmrelease-aws-ebs-csi-driver.yaml
- helmrelease-aws-efs-csi-driver.yaml
- helmrelease-aws-load-balancer-controller.yaml
