#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: velero
#  namespace: flux-system
#spec:
#  chart:
#    spec:
#      chart: velero
#      sourceRef:
#        kind: HelmRepository
#        name: velero
#      version: 2.23.5
#  install:
#    createNamespace: true
#    disableWait: false
#    remediation:
#      retries: -1
#  interval: 5m
#  storageNamespace: velero
#  targetNamespace: velero
#  values:
#    initContainers:
#    - name: velero-plugin-for-aws
#      image: velero/velero-plugin-for-aws:v1.2.0
#      volumeMounts:
#      - mountPath: /target
#        name: plugins
#
#    configuration:
#      provider: aws
#
#      backupStorageLocation:
#        name: default
#        prefix: velero/${cluster_name}-${suffix}
#        bucket: ### TODO: UPDATE HERE ###
#        config:
#          region: ### TODO: UPDATE HERE ###
#
#      volumeSnapshotLocation:
#        name: default
#        config:
#          region: ### TODO: UPDATE HERE ###
#
#    credentials:
#      useSecret: true
#      secretContents:
#        cloud: |-
#          [default]
#          aws_access_key_id= ### TODO: UPDATE HERE ###
#          aws_secret_access_key= ### TODO: UPDATE HERE ###
#          aws_region= ### TODO: UPDATE HERE ###
#
#    tolerations:
#    - effect: NoSchedule
#      key: dedicated
#      value: infra
#    - effect: NoSchedule
#      key: CriticalAddonsOnly
#
#    nodeSelector:
#      role: infra
#
#    resources:
#      requests:
#        memory: 256Mi
#        cpu: 100m
#      limits:
#        memory: 1Gi
#        cpu: 500m
#
#    metrics:
#      enabled: true
