apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
      version: '*'
  install:
    createNamespace: false
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 5m
  releaseName: aws-load-balancer-controller
  storageNamespace: kube-system
  targetNamespace: kube-system
  values:

    replicaCount: 2
    
    image:
      repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-load-balancer-controller
      tag: v2.4.1
      pullPolicy: IfNotPresent
    
    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""
    
    ##### NOME DO CLUSTER NA AWS/EKS
    clusterName: teste
    
    serviceAccount:
      create: true
      annotations:
        #### INFORMAR A ROLE DE AWS-LOADBALANCERCONTROLLER
        eks.amazonaws.com/role-arn: arn:aws:iam::311258036714:role/AmazonEKSLoadBalancerControllerRole
      name:
      automountServiceAccountToken: true
    
    #### SE USAR O CERTMANAGER PARA GERAR CERTIFICADOS LETSENCRIPT COM NLB(SOMENTE) 
    enableCertManager: true
    
    ingressClass: alb
    
    ingressClassParams:
      create: true
      name:
      spec: {}
    
    createIngressClassResource: true
    
    # Set the controller log level - info(default), debug (default "info")
    logLevel:
    
