apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/
- helmrelease-metrics-server.yaml
- helmrelease-aws-load-balancer-controller.yaml

patchesStrategicMerge: []
# - helmrelease-falco.yaml
