apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

patches:
- excludes.yaml
#- path: helmrelease-cert-manager.yaml
#- path: helmrelease-ingress-nginx.yaml
#- path: helmrelease-monitoring.yaml
#- path: helmrelease-velero.yaml
