apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  values:
    controller:
      service:
        annotations:
          # aks
          service.beta.kubernetes.io/azure-load-balancer-internal: true
