apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

patchesStrategicMerge:
- excludes.yaml
- helmrelease-ingress-nginx.yaml
- helmrelease-logging.yaml
- helmrelease-monitoring.yaml
- helmrelease-velero.yaml

patchesJson6902: []
