apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/
- clusterrolebinding-scc-monitoring.yaml
- helmrelease-cert-utils-operator.yaml
- helmrepository.yaml
- openshift-adp.yaml

patchesStrategicMerge:
- helmrelease-cert-manager-config.yaml
- helmrelease-linkerd.yaml
- excludes.yaml

patches: []
#- target:
#    kind: Deployment
#    name: example
#    namespace: my-app
#  patch: |-
#    - op: add
#      path: /spec/template/spec/hostNetwork
#      value: true
#    - op: replace
#      path: /spec/template/spec/containers/0/args/3
#      value: "--some-param"
#    - op: add
#      path: /spec/template/spec/containers/0/env/-
#      value:
#        name: AWS_REGION
#        value: "us-east-1"
