apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  values:
    controller:
      replicaCount: 1
      autoscaling:
        enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      podSecurityPolicy:
        enabled: true
      service:
        enabled: true
        type: NodePort

    defaultBackend:
      enabled: false
