apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/
- helmrelease-metrics-server.yaml

patchesStrategicMerge:
- helmrelease-ingress-nginx.yaml
- helmrelease-monitoring.yaml
- helmrelease-velero.yaml
