apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tns
  name: tns
spec:
  endpoints:
  - interval: 30s
    targetPort: http-metrics
  selector:
    matchLabels:
      demo: "true"
