apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aqua
      version: "~> 0.3"
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: trivy-operator
  storageNamespace: trivy-system
  targetNamespace: trivy-system
  values:
    trivy:
      ignoreUnfixed: false
      # severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
      severity: MEDIUM,HIGH,CRITICAL

    resources:
      requests:
        cpu: 100m
        memory: 100M
      limits:
        cpu: 200m
        memory: 200M

    serviceMonitor:
      enabled: true
      interval: "300s"
