apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: monitoring-config
      sourceRef:
        kind: HelmRepository
        name: getupcloud
      version: 0.2.0
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: monitoring
  storageNamespace: monitoring
  targetNamespace: monitoring
  values:
    cronitor:
      enabled: false
      id: ""

    backup:
      velero:
        enabled: false

    ingress:
      auth:
        basic_username: "monitoring"
        basic_password: "monitoring"

    loki:
      namespace: logging
      canary:
        tolerations:
        - key: dedicated
          value: infra
          effect: NoSchedule
        nodeSelector:
          role: infra
      ingress:
        enabled: false
        #auth:
        #  basic_username: "logging"
        #  basic_password: "logging"
