name: Build and Release

on: workflow_dispatch
  #push:
  #  branches:
  #    - "**"
  #  tags:
  #    - "v*.*.*"
  #pull_request:
  #  branches:
  #   - "main"

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set variables
      run: |-
        {
          echo "VERSION=$(cat version.txt)"
          echo "RELEASE=v$(cat version.txt)"
          echo "GIT_COMMIT=${GITHUB_SHA:0:7}"
        } >> $GITHUB_ENV
        
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull (Base image)
      id: docker_pull_base
      run: docker pull ${{ env.IMAGE }}-base:${{ env.RELEASE }} || true

    - name: Build and push (Base image)
      id: docker_build_base
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.centos8.base.x86_64
        pull: true
        push: true
        build-args: VERSION=${{ env.VERSION }} RELEASE=${{ env.RELEASE }} GIT_COMMIT=${{ env.GIT_COMMIT}}
        tags: ${{ env.IMAGE }}-base:latest,${{ env.IMAGE }}-base:${{ env.RELEASE }}

    - name: Build and push (Final image)
      id: docker_build_final
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.centos8
        pull: true
        push: true
        build-args: VERSION=${{ env.VERSION }} RELEASE=${{ env.RELEASE }} GIT_COMMIT=${{ env.GIT_COMMIT}}
        tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${{ env.RELEASE }}
