name: Build and Release

on: workflow_dispatch
  #push:
  #  branches:
  #    - "**"
  #  tags:
  #    - "v*.*.*"
  #pull_request:
  #  branches:
  #   - "main"

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set variables
      id: prep
      run: |-
        echo ::set-output name=VERSION::$(cat version.txt)
        echo ::set-output name=RELEASE::v$(cat version.txt)
        echo ::set-output name=GIT_COMMIT::${GITHUB_SHA:0:7}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-cache-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-buildx

    - name: Build and push
      id: docker_build_base
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile.centos8.base.x86_64
        pull: false
        push: true
        build-args: VERSION=${{ steps.prep.outputs.VERSION }} RELEASE=${{ steps.prep.outputs.RELEASE }} GIT_COMMIT=${{ steps.prep.outputs.GIT_COMMIT}}
        tags: ${{ steps.prep.outputs.IMAGE }}-base:latest,${{ steps.prep.outputs.IMAGE }}-base:${{ steps.prep.outputs.RELEASE }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    # Temp fix - cache grows too fast
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
