name: Build and Push

on: workflow_dispatch
  #push:
  #  branches:
  #    - "**"
  #  tags:
  #    - "v*.*.*"
  #pull_request:
  #  branches:
  #   - "main"

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set variables
      run: |-
        {
          echo "VERSION=$(cat version.txt)"
          echo "RELEASE=v$(cat version.txt)"
          echo "GIT_COMMIT=${GITHUB_SHA:0:7}"
        } >> $GITHUB_ENV
        
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Pull base image
      id: pull_base_image
      run: docker pull ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-base:v${{ env.VERSION }}
      continue-on-error: true

  build:
    needs: prepare
    runs-on: ubuntu-latest
    if: failure() && steps.pull_base_image.outcome == 'failure'   
    steps:
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.centos8.base.x86_64
        push: true
        build-args: VERSION=${{ env.VERSION }} RELEASE=${{ env.RELEASE }} GIT_COMMIT=${{ env.GIT_COMMIT}}
        
#
#    - name: GHCR-Action
#      uses: getupcloud/ghcr-action@v1
#      with:
#        token: ${{ secrets.GITHUB_TOKEN }}
#        dockerfile: Dockerfile.centos8.base.x86_64
